# fly.toml app configuration file generated for spoofspy-pgbouncer on 2023-08-27T18:31:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spoofspy-pgbouncer"
primary_region = "ams"

[env]
POSTGRESQL_PORT = "5432"
POSTGRESQL_HOST = "spoofspy-db.internal"
POSTGRESQL_USERNAME = "postgres"
PGBOUNCER_POOL_MODE = "transaction"
PGBOUNCER_BIND_ADDRESS = "::"
PGBOUNCER_MAX_CLIENT_CONN = "5000"
PGBOUNCER_DEFAULT_POOL_SIZE = "10"

[[services]]
internal_port = 6432
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 6432
handlers = ["pg_tls"]
